name: Package obs-studio
description: Packages obs-studio for specified architecture and build config
inputs:
  config:
    description: Build configuration
    required: false
    default: Release
  target:
    description: Build target for dependencies
    required: true
  package:
    description: Create platform-specific packages instead of archives
    required: false
    default: 'false'
  output-name:
    description: Custom output name for generated packages
    required: false
  codesign:
    description: Enable codesigning (macOS only)
    required: false
    default: 'false'
  codesign-ident:
    description: Developer ID for application codesigning (macOS only)
    required: false
    default: '-'
  codesign-user:
    description: Apple ID username for notarization (macOS only)
    required: false
    default: ''
  codesign-pass:
    description: Apple ID password for notarization (macOS only)
    required: false
    default: ''
  notarize:
    description: Enable notarization (macOS only)
    required: false
    default: 'false'
  path:
    description: Source for intermediary build artifacts and destination of packages.
    required: false
    default: ${{ runner.temp }}
  working-directory:
    description: Working directory for packaging
    required: false
    default: ${{ github.workspace }}
runs:
  using: composite
  steps:
    - name: Create macOS Package
      if: runner.os == 'macOS'
      shell: bash --noprofile --norc -eo errexit -eo pipefail -eo nounset {0}
      working-directory: ${{ inputs.working-directory }}
      env:
        BUILD_CONFIG: ${{ inputs.config }}
        BUILD_TARGET: ${{ inputs.target }}
        BUILD_PACKAGE: ${{ inputs.package }}
        OUTPUT_NAME: ${{ inputs.output-name }}
        BUILD_CODESIGNING: ${{ inputs.codesign }}
        CODESIGN_IDENT: ${{ inputs.codesign-ident }}
        CODESIGN_IDENT_USER: ${{ inputs.codesign-user }}
        CODESIGN_IDENT_PASS: ${{ inputs.codesign-pass }}
        BUILD_NOTARIZE: ${{ inputs.notarize }}
        OUTPUT_PATH: ${{ inputs.path }}
      run: zsh --errexit --pipefail --no-rcs ${GITHUB_ACTION_PATH}/package-macos.zsh

    - name: Create Ubuntu Package
      if: runner.os == 'Linux'
      shell: bash --noprofile --norc -eo errexit -eo pipefail -eo nounset {0}
      working-directory: ${{ inputs.working-directory }}
      env:
        BUILD_CONFIG: ${{ inputs.config }}
        BUILD_TARGET: ${{ inputs.target }}
        BUILD_PACKAGE: ${{ inputs.package }}
        OUTPUT_NAME: ${{ inputs.output-name }}
        OUTPUT_PATH: ${{ inputs.path }}
      run: ${GITHUB_ACTION_PATH}/package-ubuntu.bash

    - name: Create Windows Package
      if: runner.os == 'Windows'
      shell: pwsh -command ". '{0}'"
      working-directory: ${{ inputs.working-directory }}
      env:
        BUILD_CONFIG: ${{ inputs.config }}
        BUILD_TARGET: ${{ inputs.target }}
        BUILD_PACKAGE: ${{ inputs.package }}
        OUTPUT_NAME: ${{ inputs.output-name }}
        OUTPUT_PATH: ${{ inputs.path }}
      run: . ${env:GITHUB_ACTION_PATH}/Package-Windows.ps1
