name: Setup Environment
description: Sets up common build environment values as action outputs for workflows
inputs:
  target:
    description: Build target
    required: false
    default: ''
  platform:
    description: Custom platform name to be used instead of runner operating system name.
    required: false
    default: ${{ runner.os }}
  xcode-version:
    description: Xcode version to use for workflow (macOS)
    required: false
    default: ''
  working-directory:
    description: Custom working directory with a complete obs-studio checkout
    required: false
    default: ${{ github.workspace }}
outputs:
  commit-hash:
    description: Short hash of the commit SHA that triggered the workflow.
    value: ${{ steps.setup.outputs.commit-hash }}
  codesign:
    description: Flag to enable codesigning for current workflow
    value: ${{ steps.setup.outputs.codesign }}
  notarize:
    description: Flag to enable notarization for current workflow.
    value: ${{ steps.setup.outputs.notarize }}
  package:
    description: Flag to enable artifact generation and packaging.
    value: ${{ steps.setup.outputs.package }}
  config:
    description: Build configuration to use for builds.
    value: ${{ steps.setup.outputs.config }}
  cpu-name:
    description: Canonical Apple architecture name used for builds.
    value: ${{ steps.setup-macos.outputs.cpu-name }}
  xcode-cas-path:
    description: Path to Xcode CAS compilation cache
    value: ${{ steps.setup-macos.outputs.xcode-cas-path }}
  sparkle-version:
    description: Sparkle version to use for update generation
    value: ${{ steps.setup-macos.outputs.sparkle-version}}
  sparkle-url:
    description: Download URL for Sparkle
    value: ${{ steps.setup-macos.outputs.sparkle-url}}
  sparkle-checksum:
    description: Checksum for Sparkle download
    value: ${{ steps.setup-macos.outputs.sparkle-checksum}}
  obs-update-channel:
    description: Update channel to generate Appcasts and Windows update files for
    value: ${{ steps.setup.outputs.obs-update-channel}}
  flatpak-matrix:
    description: A JSON string representing an array of Flatpak release channels.
    value: ${{ steps.setup-ubuntu.outputs.flatpak-matrix }}
  pvs-studio-versipn:
    description: PVS-Studio version for static code analysis on Windows
    value: ${{ steps.setup-windows.outputs.pvs-studio-version}}
  pvs-studio-url:
    description: Download URL for PVS-Studio
    value: ${{ steps.setup-windows.outputs.pvs-studio-url}}
  pvs-studio-checksum:
    description: Checksum for PVS-Studio download
    value: ${{ steps.setup-windows.outputs.pvs-studio-checksum}}
  valid-version-tag:
    description: Flag for current tag passing release version requirement checks.
    value: ${{ steps.setup.outputs.valid-version-tag }}
  output-name:
    description: A prefix string usable for the names and file patterns of generated build artifacts
    value: ${{ steps.setup.outputs.output-name }}
runs:
  using: composite
  steps:
    - name: Setup Environment
      id: setup
      shell: bash --noprofile --norc -eo errexit -eo pipefail -eo nounset {0}
      working-directory: ${{ inputs.working-directory }}
      env:
        PLATFORM: ${{ inputs.platform }}
        TARGET: ${{ inputs.target }}
        GITHUB_EVENT_NUMBER: ${{ github.event.number }}
        GH_TOKEN: ${{ github.token }}
      run: ${GITHUB_ACTION_PATH}/setup-environment.bash

    - name: Setup Windows
      id: setup-windows
      if: runner.os == 'Windows'
      shell: pwsh -command ". '{0}'"
      working-directory: ${{ inputs.working-directory }}
      env:
        TARGET: ${{ inputs.target }}
      run: . ${env:GITHUB_ACTION_PATH}/Setup-Windows.ps1

    - name: Setup macOS
      id: setup-macos
      if: runner.os == 'macOS'
      shell: bash --noprofile --norc -eo errexit -eo pipefail -eo nounset {0}
      working-directory: ${{ inputs.working-directory }}
      env:
        TARGET: ${{ inputs.target }}
        XCODE_VERSION: ${{ inputs.xcode-version }}
      run: zsh --errexit --no-rcs ${GITHUB_ACTION_PATH}/setup-macos.zsh

    - name: Setup Ubuntu
      id: setup-ubuntu
      if: runner.os == 'Linux'
      shell: bash --noprofile --norc -eo errexit -eo pipefail -eo nounset {0}
      working-directory: ${{ inputs.working-directory }}
      run: ${GITHUB_ACTION_PATH}/setup-ubuntu.bash
      env:
        TARGET: ${{ inputs.target }}
