name: Run PVS-Studio
description: Runs PVS-Studio with the provided Visual Studio project and uploads results as artifacts
inputs:
  architecture:
    description: Build architecture used for project build
    required: true
  upload-codeql:
    description: Enable automatic upload of SARIF report to CodeQL
    default: 'false'
  github-token:
    description: The GitHub token used to make authenticated API requests.
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - name: Check Runner Operating System
      if: runner.os != 'Windows'
      shell: bash --noprofile --norc -eo pipefail {0}
      run: |
        : Check Runner Operating System
        print '::error::analyze-obs/run-pvs-studio action requires a Windows-based runner.'
        return 1

    - name: Build OBS Studio
      id: build
      uses: ./.github/actions/build-obs
      with:
        config: Debug
        target: ${{ inputs.architecture }}
        path: ${{ runner.temp }}

    - name: Invoke PVS-Studio
      id: analyze
      shell: pwsh -command ". '{0}'"
      env:
        BUILD_SOLUTION: ${{ format('{0}/build_{1}/obs-studio.sln?', runner.temp, inputs.architecture) }}
        BUILD_ARCHITECTURE: ${{ inputs.architecture }}
        BUILD_CONFIG: Debug
      run: . ${env:GITHUB_ACTION_PATH}/Invoke-PVSStudio.ps1

    - name: Upload PVS-Studio Output
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: 'pvs-analysis-log'
        path: |
          ${{ format('{0}/analysis.plog', runner.temp) }}
          ${{ format('{0}/analyis.plog.sarif', runner.temp) }}

    - name: Upload PVS-Studio CodeQL Report
      uses: github/codeql-action/upload-sarif@9e0d7b8d25671d64c341c19c0152d693099fb5ba # v4.35.5
      if: ${{ fromJSON(inputs.upload-codeql) }}
      with:
        sarif_file: ${{ format('{0}/analyis.plog.sarif', runner.temp) }}
        category: 'PVS-Studio (Windows)'
