name: Generate Documentation
description: Updates sphinx-based documentation
inputs:
  sourceDirectory:
    description: Path to repository checkout
    required: false
    default: ${{ github.workspace }}
runs:
  using: composite
  steps:
    - name: Check Runner Operating System 🏃‍♂️
      if: ${{ runner.os == 'macos' || runner.os == 'Windows' }}
      shell: bash
      run: echo "services-validation action requires a Linux-based runner."; exit 2
    - name: Update version number and copyright ↗️
      shell: bash
      run: |
        : "${major:=}"
        : "${minor:=}"
        : "${patch:=}"

        read -r _ major _ minor _ patch _ <<< \
          "$(grep "#define LIBOBS_API_*" ${{ inputs.sourceDirectory }}/libobs/obs-config.h \
            | sed 's/#define //g' \
            | tr -d '\' \
            | tr -s ' ' \
            | tr '\n' ' ')"

        sed -i -E \
          -e "s/version = '([0-9]+\.[0-9]+\.[0-9]+)'/version = '${major}.${minor}.${patch}'/g" \
          -e "s/release = '([0-9]+\.[0-9]+\.[0-9]+)'/release = '${major}.${minor}.${patch}'/g" \
          -e "s/copyright = '(2017-[0-9]+, Hugh Bailey)'/copyright = '2017-$(date +"%Y"), Hugh Bailey'/g" \
          ${{ inputs.sourceDirectory }}/docs/sphinx/conf.py
    - name: Install Sphinx 📜
      uses: totaldebug/sphinx-publish-action@1.2.0
      with:
        sphinx_src: ${{ inputs.sourceDirectory }}/docs/sphinx
        build_only: true
        target_branch: master
        target_path: '../home/_build'
        pre_build_commands: 'pip install -Iv sphinx==5.1.1'
    - uses: actions/upload-artifact@v3
      with:
        name: 'OBS Studio Docs ${{ steps.setup.outputs.commitHash }}'
        path: |
          ${{ runner.temp }}/_github_home/_build
          !${{ runner.temp }}/_github_home/_build/.doctrees
