name: Validate UI XML
description: Validates Qt XML files
inputs:
  failCondition:
    description: Should checks result in error response
    required: false
    default: 'never'
  workingDirectory:
    description: Working directory for checks
    required: false
    default: ${{ github.workspace }}
runs:
  using: composite
  steps:
    - name: Check Runner Operating System 🏃‍♂️
      if: ${{ runner.os == 'macos' || runner.os == 'windows' }}
      shell: bash
      run: echo "services-validation action requires a Linux-based runner."; exit 2
    - name: Install xmllint 🕵️
      shell: bash
      run: |
        sudo apt-get -qq update
        sudo apt-get install --no-install-recommends -y libxml2-utils
    - name: Register Annotations 📝
      uses: korelstar/xmllint-problem-matcher@v1
    - name: Validate XML 💯
      shell: bash
      run: |
        if [[ '${{ inputs.failCondition }}' == 'error' ]]; then
          set -e
        fi

        xmllint \
          --schema ${{ github.workspace }}/UI/forms/XML-Schema-Qt5.15.xsd \
          --noout \
            ${{ github.workspace }}/UI/forms/*.ui \
            ${{ github.workspace }}/UI/forms/**/*.ui
