name: Run clang-analyze
description: Runs clang-analyze on OBS Studio
inputs:
  architecture:
    description: Build architecture used for project build
    required: true
  upload-codeql:
    description: Enable automatic upload of SARIF report to CodeQL
    default: 'false'
runs:
  using: composite
  steps:
    - name: Check Runner Operating System
      if: runner.os == 'Windows'
      shell: bash --noprofile --norc -eo pipefail {0}
      run: |
        : Check Runner Operating System
        print '::error::analyze-obs/run-clang-analyze action requires a macOS- or Ubuntu-based runner.'
        return 1

    - name: Build OBS Studio
      id: build
      uses: ./.github/actions/build-obs
      with:
        config: Debug
        target: ${{ inputs.architecture }}
        analyze: true
        codesign: false
        xcode-version: ${{ env.XCODE_VERSION || '26.6' }}

    - name: Gather SARIF files
      if: runner.os == 'macOS'
      shell: bash --noprofile --norc -eo errexit -eo pipefail -eo nounset {0}
      working-directory: ${{ inputs.working-directory }}
      env:
        ANALYTICS_PATH: ${{ steps.build.outputs.analyzer-output-path }}
      run: zsh --errexit --pipefail --no-rcs ${GITHUB_ACTION_PATH}/gather-sarif-files.zsh

    - name: Merge SARIF files
      id: merge
      uses: ./.github/actions/analyze-obs/merge-clang-sarif
      with:
        path: ${{ steps.build.outputs.analyzer-output-path }}
        output-name: obs-studio-${{ runner.os }}-${{ inputs.architecture }}.sarif

    - name: Upload PVS-Studio CodeQL Report
      uses: github/codeql-action/upload-sarif@9e0d7b8d25671d64c341c19c0152d693099fb5ba # v4.35.5
      if: ${{ fromJSON(inputs.upload-codeql) }}
      with:
        sarif_file: ${{ steps.merge.outputs.path }}
        category: 'clang-analyze (${{ runner.os }} ${{ inputs.architecture }})'
