name: Analyze Project
on:
  workflow_call:
    secrets:
      restream-client-id:
        description: The OAuth client-id used for Restream.io API connections.
        required: false
      restream-hash:
        description: The hash value required to decrypt the Restream.io client id.
        required: false
      twitch-client-id:
        description: The OAuth client-id used for Twitch.tv API connections.
        required: false
      twitch-hash:
        description: The hash value required to decrypt the Twitch.tv client id.
        required: false
      youtube-client-id:
        description: The OAuth client-id used for Youtube.com API connections.
        required: false
      youtube-client-hash:
        description: The hash value required to decrypt the Youtube.com client id.
        required: false
      yotube-client-secret:
        description: The OAuth client secret used for Youtube.com API connections.
        required: false
      yotube-client-secret-hash:
        description: The hash value required to decrypt the Youtube.com client secret.
        required: false
      pvs-license-name:
        description: PVS license holder name
        required: false
      pvs-license-key:
        description: PVS license key name
        required: false
permissions: {}
defaults:
  run:
    shell: bash --noprofile --norc -eo errexit -eo pipefail -eo nounset {0}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  windows:
    name: Windows (PVS-Studio)
    runs-on: windows-2025-vs2026
    if: fromJSON(vars.ENABLE_PVS_STUDIO)
    permissions:
      contents: read          # Necessary for repository checkouts.
      security-events: write  # Necessary to post CodeQL security scanning reports
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          submodules: recursive
          fetch-depth: 1

      - name: Set Up Environment
        id: setup
        run: |
          : Set Up Environment
          if [[ -n "${RUNNER_DEBUG:-}" ]]; then set -x; fi

          jq -r '.configurePresets[]
            | select(.name == "dependencies")
            | .vendor["obsproject.com/obs-studio"].tools.["pvs-studio"]
            | to_entries
            | map("\(.key)=\(.value|tostring)")
            | .[]' "${PWD}/CMakePresets.json" >> "${GITHUB_OUTPUT}"

      - name: Setup PVS-Studio
        id: pvs-setup
        uses: ./.github/actions/analyze-obs/setup-pvs-studio
        with:
          version: ${{ steps.setup.outputs.version }}
          checksum: ${{ steps.setup.outputs.hash }}
          url: ${{ steps.setup.outputs.baseUrl }}
          user: ${{ secrets.pvs-license-name }}
          license: ${{ secrets.pvs-license-key }}

      - name: Analyze OBS Studio
        id: analyze
        uses: ./.github/actions/analyze-obs/run-pvs-studio
        with:
          architecture: x64
          upload-codeql: true

  macos:
    name: macOS (clang-analyze)
    runs-on: macos-26
    permissions:
      contents: read          # Necessary for repository checkouts.
      security-events: write  # Necessary to post CodeQL security scanning reports
    env:
      XCODE_VERSION: '26.6'
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          submodules: recursive
          fetch-depth: 1

      - name: Analyze OBS Studio
        id: analyze
        uses: ./.github/actions/analyze-obs/run-clang-analyze
        env:
          RESTREAM_CLIENTID: ${{ secrets.restream-client-id }}
          RESTREAM_HASH: ${{ secrets.restream-hash }}
          TWITCH_CLIENTID: ${{ secrets.twitch-client-id }}
          TWITCH_HASH: ${{ secrets.twitch-hash }}
          YOUTUBE_CLIENTID: ${{ secrets.youtube-client-id }}
          YOUTUBE_CLIENTID_HASH: ${{ secrets.youtube-hash }}
          YOUTUBE_SECRET: ${{ secrets.youtube-client-secret }}
          YOUTUBE_SECRET_HASH: ${{ secrets.youtube-client-secret-hash }}
        with:
          architecture: arm64
          upload-codeql: true
