name: Build Project
on:
  workflow_call:
    secrets:
      macos-signing-identity:
        description: The Apple Developer identity used for code signing on macOS.
        required: false
      macos-signing-certificate:
        description: The base64-encoded Apple Developer certificate used for code signing on macOS.
        required: false
      macos-signing-password:
        description: The password required to unlock the Apple Developer certificate.
        required: false
      macos-provisioning-profile:
        description: The provisioning profile used for code signing on macOS.
        required: false
      macos-notarization-user:
        description: The Apple ID used for notarization on macOS.
        required: false
      macos-notarization-password:
        description: The application password created for notarization on macOS.
        required: false
      restream-client-id:
        description: The OAuth client-id used for Restream.io API connections.
        required: false
      restream-hash:
        description: The hash value required to decrypt the Restream.io client id.
        required: false
      twitch-client-id:
        description: The OAuth client-id used for Twitch.tv API connections.
        required: false
      twitch-hash:
        description: The hash value required to decrypt the Twitch.tv client id.
        required: false
      youtube-client-id:
        description: The OAuth client-id used for Youtube.com API connections.
        required: false
      youtube-client-hash:
        description: The hash value required to decrypt the Youtube.com client id.
        required: false
      yotube-client-secret:
        description: The OAuth client secret used for Youtube.com API connections.
        required: false
      yotube-client-secret-hash:
        description: The hash value required to decrypt the Youtube.com client secret.
        required: false
      gpu-priority-val:
        description: Custom GPU priority value for libobs.
        required: false
permissions:
  contents: read    # Necessary for repository checkouts.
defaults:
  run:
    shell: bash --noprofile --norc -eo errexit -eo pipefail -eo nounset {0}
jobs:
  build-obs:
    name: OBS Studio
    strategy:
      fail-fast: false
      matrix:
        os: [macos-26, ubuntu-26.04, ubuntu-24.04, windows-2025-vs2026]
        architecture: [x86_64, arm64]
        include:
          - os: macos-26
            name: macos
            cache-dir: CompilationCache.noindex
          - os: windows-2025-vs2026
            name: windows
          - os: ubuntu-26.04
            name: ubuntu-26.04
            cache-dir: .ccache
          - os: ubuntu-24.04
            name: ubuntu-24.04
            cache-dir: .ccache
        exclude:
          - os: ubuntu-26.04
            architecture: arm64
          - os: ubuntu-24.04
            architecture: arm64
    runs-on: ${{ matrix.os }}
    env:
      IS_TAG_PUSH: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
      ENABLE_MACOS_CODE_SIGNING: >-
        ${{
          matrix.name == 'macos'
          && fromJSON(vars.ENABLE_MACOS_CODE_SIGNING || 'false')
          && contains(fromJSON('["push", "workflow_dispatch", "schedule"]'), github.event_name)
        }}
      ENABLE_MACOS_NOTARIZATION: >-
        ${{
          matrix.name == 'macos'
          && fromJSON(vars.ENABLE_MACOS_NOTARIZATION || 'false')
          && github.event_name == 'push'
        }}
      ENABLE_PACKAGING: >-
        ${{ case(
          github.event_name == 'pull_request'
          && contains(github.event.labels.*.name, 'Seeking Testers'), true,
          contains(fromJSON('["push", "workflow_dispatch", "schedule"]'), github.event_name), true,
          false
        ) }}
      XCODE_VERSION: '26.6'
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          submodules: recursive
          fetch-depth: 0

      - name: Generate Semver From Tag
        id: semver
        uses: ./.github/actions/check-version-tag
        with:
          ref: ${{ github.ref_name }}

      - name: Generate Short GitHub SHA
        id: short-sha
        uses: ./.github/actions/generate-short-sha

      - name: Restore Compilation Cache
        id: compilation-cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        if: matrix.name != 'windows'
        with:
          path: ${{ format('{0}/{1}', runner.temp, matrix.cache-dir) }}
          key: >-
            ${{ format(
              '{0}-compilation-{1}-{2}',
              matrix.name, matrix.architecture,
              case(
                fromJSON(env.IS_TAG_PUSH) && fromJSON(steps.semver.outputs.is-valid-semver),
                'Release',
                'RelWithDebInfo'
              )
            ) }}
          restore-keys: |
            ${{ format('{0}-compilation-{1}-', matrix.name, matrix.architecture) }}

      - name: Set Up Code Signing
        id: codesign
        uses: ./.github/actions/codesign-obs/setup-macos
        if: fromJSON(env.ENABLE_MACOS_CODE_SIGNING)
        with:
          identity: ${{ secrets.macos-signing-identity }}
          cert: ${{ secrets.macos-signing-certificate }}
          cert-password: ${{ secrets.macos-signing-password }}
          provisioning-profile: ${{ secrets.macos-provisioning-profile }}
          apple-id: ${{ secrets.macos-notarization-user }}
          apple-secret: ${{ secrets.macos-notarization-password }}

      - name: Build OBS Studio
        id: build
        uses: ./.github/actions/build-obs
        env:
          RESTREAM_CLIENTID: ${{ secrets.restream-client-id }}
          RESTREAM_HASH: ${{ secrets.restream-hash }}
          TWITCH_CLIENTID: ${{ secrets.twitch-client-id }}
          TWITCH_HASH: ${{ secrets.twitch-hash }}
          YOUTUBE_CLIENTID: ${{ secrets.youtube-client-id }}
          YOUTUBE_CLIENTID_HASH: ${{ secrets.youtube-hash }}
          YOUTUBE_SECRET: ${{ secrets.youtube-client-secret }}
          YOUTUBE_SECRET_HASH: ${{ secrets.youtube-client-secret-hash }}
        with:
          config: >-
            ${{ case(
              fromJSON(env.IS_TAG_PUSH) && fromJSON(steps.semver.outputs.is-valid-semver),
              'Release',
              'RelWithDebInfo'
            ) }}
          target: ${{ matrix.architecture }}
          codesign: >-
            ${{
              fromJSON(env.ENABLE_MACOS_CODE_SIGNING)
              && fromJSON(steps.codesign.outputs.can-codesign)
            }}
          codesign-ident: ${{ steps.codesign.outputs.identity || '' }}
          codesign-team: ${{ steps.codesign.outputs.team  || '' }}
          provisioning-profile-id: ${{ steps.codesign.outputs.profile-uuid  || '' }}
          xcode-version: ${{ env.XCODE_VERSION || '26.6' }}
          xcode-cas-path: ${{ format('{0}/{1}', runner.temp, matrix.cache-dir) }}

      - name: Package OBS Studio
        id: package
        uses: ./.github/actions/package-obs
        if: fromJSON(env.ENABLE_PACKAGING)
        with:
          config: >-
            ${{ case(
              fromJSON(env.IS_TAG_PUSH) && fromJSON(steps.semver.outputs.is-valid-semver),
              'Release',
              'RelWithDebInfo'
            ) }}
          target: ${{ matrix.architecture }}
          package: ${{ case(github.event_name == 'pull_request', false, true) }}
          output-name: >-
            ${{ format(
              'obs-studio-{0}-{1}-{2}',
              matrix.name, matrix.architecture, steps.short-sha.outputs.sha
            ) }}
          codesign: >-
            ${{
              fromJSON(env.ENABLE_MACOS_CODE_SIGNING)
              && fromJSON(steps.codesign.outputs.can-codesign)
            }}
          codesign-ident: ${{ steps.codesign.outputs.identity || '' }}
          codesign-user: ${{ secrets.macos-notarization-user  || '' }}
          codesign-pass: ${{ secrets.macos-notarization-password  || '' }}
          notarize: >-
            ${{
              fromJSON(env.ENABLE_MACOS_CODE_SIGNING)
              && fromJSON(steps.codesign.outputs.can-notarize)
            }}

      - name: Upload Application
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: fromJSON(fromJSON(env.ENABLE_PACKAGING))
        with:
          archive: ${{ !contains(fromJSON('["macos", "windows"]'), matrix.name) }}
          name: >-
            ${{ format(
              'obs-studio-{0}-{1}-{2}',
              matrix.name, matrix.architecture, steps.short-sha.outputs.sha
            ) }}
          path: >-
            ${{ format(
              '{0}/obs-studio-{1}-{2}-{3}.*',
              runner.temp, matrix.name, matrix.architecture, steps.short-sha.outputs.sha
            ) }}

      - name: Upload Debug Symbols
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: >-
          matrix.name != 'windows'
          && fromJSON(env.IS_TAG_PUSH)
          && fromJSON(steps.semver.outputs.is-valid-semver)
        with:
          archive: ${{ matrix.name != 'macos' }}
          name: >-
            ${{ format(
              'obs-studio-{0}-{1}-{2}-debug-symbols',
              matrix.name,
              matrix.architecture, steps.short-sha.outputs.sha
            ) }}
          path: >-
            ${{ format(
              '{0}/obs-studio-{1}-{2}-{3}-debug-symbols.*',
              runner.temp, matrix.name, matrix.architecture, steps.short-sha.outputs.sha
            ) }}

      - name: Upload Developer Library
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: >-
          contains(fromJSON('["macos", "windows"]'), matrix.name)
          && fromJSON(env.IS_TAG_PUSH)
          && fromJSON(steps.semver.outputs.is-valid-semver)
        with:
          archive: false
          name: >-
            ${{ format(
              'obs-studio-{0}-{1}-{2}-plugin-dev',
              matrix.name,
              matrix.architecture, steps.short-sha.outputs.sha
            ) }}
          path: >-
            ${{ format(
              '{0}/obs-studio-{1}-{2}-{3}-plugin-dev.*',
              runner.temp, matrix.name, matrix.architecture, steps.short-sha.outputs.sha
            ) }}

      - name: Upload Source Tarball
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: >-
          matrix.name == 'ubuntu-26.04'
          && fromJSON(env.IS_TAG_PUSH)
          && fromJSON(steps.semver.outputs.is-valid-semver)
        with:
          archive: false
          name: >-
            ${{ format(
              'obs-studio-{0}-{1}-{2}-sources',
              matrix.name, matrix.architecture, steps.short-sha.outputs.sha
            ) }}
          path: >-
            ${{ format(
              '{0}/obs-studio-{1}-{2}-{3}-sources.*',
              runner.temp, matrix.name, matrix.architecture, steps.short-sha.outputs.sha
            ) }}

      - name: Save Compilation Cache
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        if: >-
          matrix.name != 'windows'
          && github.event_name != 'pull_request'
          && steps.compilation-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ format('{0}/{1}', runner.temp, matrix.cache-dir) }}
          key: >-
            ${{ format(
              '{0}-compilation-{1}-{2}',
              matrix.name, matrix.architecture,
              case(
                github.event_name == 'push'
                && github.ref_type == 'tag'
                && fromJSON(steps.semver.outputs.is-valid-semver), 'Release',
                'RelWithDebInfo'
              )
            ) }}

  flatpak-build:
    name: OBS Studio (Flatpak, x86_64)
    runs-on: ubuntu-26.04
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-25.08@sha256:364e5ede018e821ba430849690649ac7ec43d082c29ba4be3d357c517262ea1f
      options: --privileged
      volumes:
        - /opt/hostedtoolcache/CodeQL:/to_clean/codeql
        - /opt/hostedtoolcache/Python:/to_clean/python
        - /usr/local/.ghcup:/to_clean/ghcup
        - /usr/local/lib/android:/to_clean/android
        - /usr/share/dotnet:/to_clean/dotnet
        - /usr/share/swift:/to_clean/swift
    defaults:
      run:
        shell: bash --noprofile --norc -eo errexit -eo pipefail -eo nounset {0}
    env:
      FLATPAK_BUILD_SHARE_PATH: flatpak_app/files/share
      BUILD_BUNDLE: >-
        ${{ case(
          github.event_name == 'pull_request'
          && contains(github.event.labels.*.name, 'Seeking Testers'), true,
          contains(fromJSON('["push", "workflow_dispatch", "schedule"]'), github.event_name), true,
          false
        ) }}
    steps:
      - name: Prepare Container Image
        env:
          REMOVE_LIST: 'Android CodeQL GHCup Python Swift dotNET'
        run: |
          : Prepare Container Image
          if [[ -n "${RUNNER_DEBUG:-}" ]]; then set -x; fi

          declare -a removals
          read -r -a removals <<< "${REMOVE_LIST}"
          for removal in "${removals[@]}"; do
            echo "Removing ${removal} files from runner."
            rm -rf /to_clean/"${removal,,*}"/*
          done

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          submodules: recursive
          fetch-depth: 0

      - name: Add Workspace As Safe Directory
        run: |
          : Add Workspace As Safe Directory
          if [[ -n "${RUNNER_DEBUG:-}" ]]; then set -x; fi

          git config --global --add safe.directory "${GITHUB_WORKSPACE}"

      - name: Generate Semver From Tag
        id: semver
        uses: ./.github/actions/check-version-tag
        with:
          ref: ${{ github.ref_name }}

      - name: Generate Short GitHub SHA
        id: short-sha
        uses: ./.github/actions/generate-short-sha

      - name: Check Flatpak Builder Cache
        id: cache
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          : Check Flatpak Builder Cache
          if [[ -n "${RUNNER_DEBUG:-}" ]]; then set -x; fi

          declare manifest_hash
          manifest_hash="$(shasum \
            --algorithm 256 "${PWD}/build-aux/com.obsproject.Studio.json" \
            | cut -d ' ' -f 1)"

          # When provided a cache key, Flatpak-builder automatically adds the
          # build architecture to the key in case multiple architectures are built.
          # Otherwise it generates a cache-key based on the pattern:
          # 'flatpak-builder-<architecture>-<first 20 characters of manifest-hash>
          cache_key="$(gh cache list \
            --ref "refs/heads/master" \
            --key "flatpak-builder-x86_64-${manifest_hash:0:20}" \
            --limit 1 --json key --jq '.[0].key')"

          {
            if [[ -n "${cache_key}" ]]; then
              echo "cache-hit=true"
            else
              echo "cache-hit=false"
            fi
          }  >> "${GITHUB_OUTPUT}"

      - name: Validate Flatpak manifest
        uses: ./.github/actions/lint-obs/lint-flatpak-manifest
        with:
          artifact: manifest
          path: build-aux/com.obsproject.Studio.json

      - name: Build Flatpak Manifest
        uses: flatpak/flatpak-github-actions/flatpak-builder@401fe28a8384095fc1531b9d320b292f0ee45adb # v6.7
        with:
          build-bundle: ${{ fromJSON(env.BUILD_BUNDLE) }}
          bundle: ${{ format('obs-studio-flatpak-{0}.flatpak', steps.short-sha.outputs.sha) }}
          cache: >-
            ${{ fromJSON(steps.cache.outputs.cache-hit)
              || (github.event_name == 'push' && github.ref_name == 'master')
            }}
          manifest-path: ${{ format('{0}/build-aux/com.obsproject.Studio.json', github.workspace) }}
          mirror-screenshots-url: https://dl.flathub.org/media
          restore-cache: ${{ fromJSON(steps.cache.outputs.cache-hit) }}

      - name: Validate AppStream
        uses: ./.github/actions/lint-obs/lint-flatpak-manifest
        with:
          artifact: appstream
          path: ${{ format('{0}/metainfo/com.obsproject.Studio.metainfo.xml', env.FLATPAK_BUILD_SHARE_PATH) }}

      - name: Verify Icon and Metadata in app-info
        working-directory: ${{ env.FLATPAK_BUILD_SHARE_PATH }}
        run: |
          : Verify Icon and Metadata in app-info
          if [[ -n "${RUNNER_DEBUG:-}" ]]; then set -x; fi

          if ! [[ -f "${PWD}/app-info/icons/flatpak/128x128/com.obsproject.Studio.png" ]]; then
            echo '::error::Missing 128x128 icon in app-info'
            return 1
          fi

          if ! [[ -f "${PWD}/app-info/xmls/com.obsproject.Studio.xml.gz" ]]; then
            echo '::error::Missing com.obsproject.Studio.xml.gz in app-info'
            return 1
          fi

      - name: Validate build directory
        uses: ./.github/actions/lint-obs/lint-flatpak-manifest
        with:
          artifact: builddir
          path: flatpak_app

      - name: Validate repository
        uses: ./.github/actions/lint-obs/lint-flatpak-manifest
        with:
          artifact: repo
          path: repo
