name: Dispatch
run-name: Dispatched - ${{ inputs.job }}
on:
  workflow_dispatch:
    inputs:
      job:
        description: Dispatch job to run
        required: true
        type: choice
        options:
          - codeql
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read                # Necessary for repository checkouts.
defaults:
  run:
    shell: bash --noprofile --norc -eo errexit -eo pipefail -eo nounset {0}
jobs:
  analyze-project:
    name: Code Analysis
    if: inputs.job == 'codeql'
    uses: ./.github/workflows/analyze-project.yaml
    permissions:
      contents: read            # Necessary for repository checkouts.
      security-events: write    # Necessary to post CodeQL security scanning reports
    secrets: inherit            # zizmor: ignore[secrets-inherit]
