name: 'OBS (Push + Pull Request)'

on:
  push:
    paths-ignore: ['**.md']
    branches: [master]
    tags: ['*']
  pull_request:
    paths-ignore: ['**.md']
    branches: [master]

env:
  CEF_BUILD_VERSION_MAC: '4183'
  CEF_BUILD_VERSION_LINUX: '4280'
  CEF_BUILD_VERSION_WIN: '3770'
  QT_VERSION_MAC: '5.15.2'
  QT_VERSION_WIN: '5.15.2'
  DEPS_VERSION_MAC: '2021-02-28'
  DEPS_VERSION_WIN: '2019'
  VLC_VERSION_MAC: '3.0.8'
  VLC_VERSION_WIN: '3.0.0-git'
  TWITCH_CLIENTID: ${{ secrets.TWITCH_CLIENT_ID }}
  TWITCH_HASH: ${{ secrets.TWITCH_HASH }}
  RESTREAM_CLIENTID: ${{ secrets.RESTREAM_CLIENTID }}
  RESTREAM_HASH: ${{ secrets.RESTREAM_HASH }}

jobs:
  001_clang_check:
    name: 'Code Format Check'
    runs-on: [ubuntu-latest]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.3
        with:
          submodules: 'recursive'

      - name: 'Install clang-format'
        run: sudo apt-get install -y clang-format-10

      - name: 'Run clang-format'
        run: |
          ./formatcode.sh
          ./CI/check-format.sh

  002_macos_build:
    name: 'macOS (Latest)'
    runs-on: [macos-latest]
    needs: [001_clang_check]
    env:
      MIN_MACOS_VERSION: '10.13'
      SPARKLE_VERSION: '1.23.0'
      BLOCKED_FORMULAS: 'openssl@1.0.2t python@2.7.17 speexdsp curl php'
    defaults:
      run:
        shell: bash
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.3
        with:
          submodules: 'recursive'

      - name: 'Check for Github Labels'
        if: github.event_name == 'pull_request'
        run: |
          LABELS_URL="$(echo ${{ github.event.pull_request.url }} | sed s'/pulls/issues/')"
          LABEL_FOUND="$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "${LABELS_URL}/labels" | sed -n 's/.*"name": "\(.*\)",/\1/p' | grep 'Seeking Testers' || true)"
          if [ "${LABEL_FOUND}" = "Seeking Testers" ]; then
            echo "SEEKING_TESTERS=1" >> $GITHUB_ENV
          else
            echo "SEEKING_TESTERS=0" >> $GITHUB_ENV
          fi

      - name: 'Setup build environment (Homebrew + ENV)'
        run: |
          git fetch --prune --unshallow
          echo "OBS_GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          echo "OBS_GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "OBS_GIT_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

          echo "NPROC=$(sysctl -n hw.ncpu)" >> $GITHUB_ENV

          REMOVE_FORMULAS=''
          for FORMULA in "${{ env.BLOCKED_FORMULAS }}"; do
            if [ -d "/usr/local/opt/${FORMULA}" ]; then
              if [ "${FORMULA}" = "openssl@1.0.2t" ]; then brew untap local/openssl;
              elif [ "${FORMULA}" = "python@2.7.17" ]; then brew untap local/python2; fi

              REMOVE_FORMULAS="${REMOVE_FORMULAS} ${FORMULA}"
            fi
          done

          brew uninstall ${REMOVE_FORMULAS}
          brew bundle --file ./CI/scripts/macos/Brewfile

          mkdir ${{ github.workspace }}/build
          mkdir ${{ github.workspace }}/nightly

      - name: 'Restore Chromium Embedded Framework from cache'
        id: cef-cache
        uses: actions/cache@v2.1.2
        env:
          CACHE_NAME: 'cef-cache'
        with:
          path: ${{ github.workspace }}/CI_BUILD/cef_binary_${{ env.CEF_BUILD_VERSION_MAC }}_macosx64
          key: ${{ runner.os }}-pr-${{ env.CACHE_NAME }}-${{ env.CEF_BUILD_VERSION_MAC }}

      - name: 'Restore VLC dependency from cache'
        id: vlc-cache
        uses: actions/cache@v2.1.2
        env:
          CACHE_NAME: 'vlc-cache'
        with:
          path: ${{ github.workspace }}/CI_BUILD/vlc-${{ env.VLC_VERSION_MAC }}
          key: ${{ runner.os }}-pr-${{ env.CACHE_NAME }}-${{ env.VLC_VERSION_MAC }}

      - name: 'Restore Sparkle dependency from cache'
        id: sparkle-cache
        uses: actions/cache@v2.1.2
        env:
          CACHE_NAME: 'sparkle-cache'
        with:
          path: ${{ github.workspace }}/CI_BUILD/sparkle
          key: ${{ runner.os }}-pr-${{ env.CACHE_NAME }}-${{ env.SPARKLE_VERSION }}

      - name: 'Install dependencies'
        env:
          INSTALL_VLC: ${{ !steps.vlc-cache.outputs.cache-hit }}
          INSTALL_SPARKLE: ${{ !steps.sparkle-cache.outputs.cache-hit }}
          INSTALL_CEF: ${{ !steps.cef-cache.outputs.cache-hit }}
        run: |
          echo "  + Installing dependencies v${{ env.DEPS_VERSION_MAC }}"
          curl -L -O https://github.com/obsproject/obs-deps/releases/download/${{ env.DEPS_VERSION_MAC }}/macos-deps-${{ env.DEPS_VERSION_MAC }}.tar.gz
          tar -xf ./macos-deps-${{ env.DEPS_VERSION_MAC }}.tar.gz -C "/tmp"

          echo "  + Installing Qt v${{ env.QT_VERSION_MAC }}"
          curl -L -O https://github.com/obsproject/obs-deps/releases/download/${{ env.DEPS_VERSION_MAC }}/macos-qt-${{ env.QT_VERSION_MAC }}-${{ env.DEPS_VERSION_MAC }}.tar.gz
          tar -xf ./macos-qt-${{ env.QT_VERSION_MAC }}-${{ env.DEPS_VERSION_MAC }}.tar.gz -C "/tmp"

          xattr -r -d com.apple.quarantine /tmp/obsdeps

          if [ "${INSTALL_VLC}" = "true" ]; then
            echo "  + Installing dependency VLC v${{ env.VLC_VERSION_MAC }}"
            curl -L -O https://downloads.videolan.org/vlc/${{ env.VLC_VERSION_MAC }}/vlc-${{ env.VLC_VERSION_MAC }}.tar.xz
            if [ ! -d "${{ github.workspace }}/CI_BUILD" ]; then mkdir "${{ github.workspace }}/CI_BUILD"; fi
            tar -xf ./vlc-${{ env.VLC_VERSION_MAC }}.tar.xz -C "${{ github.workspace }}/CI_BUILD"
          fi

          if [ "${INSTALL_SPARKLE}" = "true" ]; then
            echo "  + Installing dependency Sparkle v${{ env.SPARKLE_VERSION }}"
            curl -L -o sparkle.tar.bz2 https://github.com/sparkle-project/Sparkle/releases/download/${{ env.SPARKLE_VERSION }}/Sparkle-${{ env.SPARKLE_VERSION }}.tar.bz2
            mkdir ${{ github.workspace }}/CI_BUILD/sparkle
            tar -xf ./sparkle.tar.bz2 -C ${{ github.workspace }}/CI_BUILD/sparkle
          fi
          sudo cp -R ${{ github.workspace }}/CI_BUILD/sparkle/Sparkle.framework /Library/Frameworks/Sparkle.framework

          if [ "${INSTALL_CEF}" = "true" ]; then
            echo "  + Installing dependency Chromium Embedded Framework (CEF) v${{ env.CEF_BUILD_VERSION_MAC }}"

            curl -L -O https://cdn-fastly.obsproject.com/downloads/cef_binary_${{ env.CEF_BUILD_VERSION_MAC }}_macosx64.tar.bz2
            tar -xf ./cef_binary_${{ env.CEF_BUILD_VERSION_MAC }}_macosx64.tar.bz2 -C ${{ github.workspace }}/CI_BUILD/
            cd ${{ github.workspace }}/CI_BUILD/cef_binary_${{ env.CEF_BUILD_VERSION_MAC }}_macosx64
            /usr/bin/sed -i '.orig' '/add_subdirectory(tests\/ceftests)/d' ./CMakeLists.txt
            /usr/bin/sed -i '.orig' s/\"10.9\"/\"${{ env.MIN_MACOS_VERSION }}\"/ ./cmake/cef_variables.cmake
            mkdir build && cd build
            cmake  -DCMAKE_CXX_FLAGS="-std=c++11 -stdlib=libc++ -Wno-deprecated-declarations" -DCMAKE_EXE_LINKER_FLAGS="-std=c++11 -stdlib=libc++" -DCMAKE_OSX_DEPLOYMENT_TARGET=${{ env.MIN_MACOS_VERSION }}  ..
            make -j${NPROC:-4}
            mkdir libcef_dll
            cd ${{ github.workspace }}
          fi

      - name: 'Build OBS'
        working-directory: '${{ github.workspace }}/build'
        run: |
          LEGACY_BROWSER="$(test "${{ env.CEF_BUILD_VERSION_MAC }}" -le 3770 && echo "ON" || echo "OFF")"
          cmake -DENABLE_UNIT_TESTS=YES -DENABLE_SPARKLE_UPDATER=ON -DCMAKE_OSX_DEPLOYMENT_TARGET=${{ env.MIN_MACOS_VERSION }} -DQTDIR="/tmp/obsdeps" -DSWIGDIR="/tmp/obsdeps" -DDepsPath="/tmp/obsdeps" -DVLCPath="${{ github.workspace }}/CI_BUILD/vlc-${{ env.VLC_VERSION }}" -DENABLE_VLC=ON -DBUILD_BROWSER=ON -DBROWSER_LEGACY=$LEGACY_BROWSER -DWITH_RTMPS=ON -DCEF_ROOT_DIR="${{ github.workspace }}/CI_BUILD/cef_binary_${{ env.CEF_BUILD_VERSION_MAC }}_macosx64" -DTWITCH_CLIENTID='${{ env.TWITCH_CLIENTID }}' -DTWITCH_HASH='${{ env.TWITCH_HASH }}' -DRESTREAM_CLIENTID='${{ env.RESTREAM_CLIENTID }}' -DRESTREAM_HASH='${{ env.RESTREAM_HASH }}' ..

          make -j${NPROC:-4}

      - name: 'Run tests'
        if: success()
        working-directory: ${{ github.workspace }}/build
        run: make CTEST_OUTPUT_ON_FAILURE=1 test

      - name: 'Create build artifact'
        if: success() && (github.event_name != 'pull_request' || env.SEEKING_TESTERS == '1')
        working-directory: ${{ github.workspace }}/build
        run: |
          if [ -d ./OBS.app ]; then rm -rf ./OBS.app; fi
          mkdir -p OBS.app/Contents/MacOS
          mkdir OBS.app/Contents/PlugIns
          mkdir OBS.app/Contents/Resources
          mkdir OBS.app/Contents/Frameworks

          cp rundir/RelWithDebInfo/bin/obs ./OBS.app/Contents/MacOS
          cp rundir/RelWithDebInfo/bin/obs-ffmpeg-mux ./OBS.app/Contents/MacOS
          if ! [ "${{ env.CEF_BUILD_VERSION_MAC }}" -le 3770 ]; then
            cp -R "rundir/RelWithDebInfo/bin/OBS Helper.app" "./OBS.app/Contents/Frameworks/OBS Helper.app"
            cp -R "rundir/RelWithDebInfo/bin/OBS Helper (GPU).app" "./OBS.app/Contents/Frameworks/OBS Helper (GPU).app"
            cp -R "rundir/RelWithDebInfo/bin/OBS Helper (Plugin).app" "./OBS.app/Contents/Frameworks/OBS Helper (Plugin).app"
            cp -R "rundir/RelWithDebInfo/bin/OBS Helper (Renderer).app" "./OBS.app/Contents/Frameworks/OBS Helper (Renderer).app"
          fi

          cp rundir/RelWithDebInfo/bin/libobsglad.0.dylib ./OBS.app/Contents/MacOS
          cp -R rundir/RelWithDebInfo/data ./OBS.app/Contents/Resources
          cp ../CI/scripts/macos/app/AppIcon.icns ./OBS.app/Contents/Resources
          cp -R rundir/RelWithDebInfo/obs-plugins/ ./OBS.app/Contents/PlugIns
          cp ../CI/scripts/macos/app/Info.plist ./OBS.app/Contents

          if [ -d ./OBS.app/Contents/Resources/data/obs-scripting ]; then
            mv ./OBS.app/Contents/Resources/data/obs-scripting/obslua.so ./OBS.app/Contents/MacOS/
            mv ./OBS.app/Contents/Resources/data/obs-scripting/_obspython.so ./OBS.app/Contents/MacOS/
            mv ./OBS.app/Contents/Resources/data/obs-scripting/obspython.py ./OBS.app/Contents/MacOS/
            rm -rf ./OBS.app/Contents/Resources/data/obs-scripting/
          fi

          BUNDLE_PLUGINS=(
            ./OBS.app/Contents/PlugIns/coreaudio-encoder.so
            ./OBS.app/Contents/PlugIns/decklink-ouput-ui.so
            ./OBS.app/Contents/PlugIns/decklink-captions.so
            ./OBS.app/Contents/PlugIns/frontend-tools.so
            ./OBS.app/Contents/PlugIns/image-source.so
            ./OBS.app/Contents/PlugIns/mac-avcapture.so
            ./OBS.app/Contents/PlugIns/mac-capture.so
            ./OBS.app/Contents/PlugIns/mac-decklink.so
            ./OBS.app/Contents/PlugIns/mac-syphon.so
            ./OBS.app/Contents/PlugIns/mac-vth264.so
            ./OBS.app/Contents/PlugIns/mac-virtualcam.so
            ./OBS.app/Contents/PlugIns/obs-browser.so
            ./OBS.app/Contents/PlugIns/obs-ffmpeg.so
            ./OBS.app/Contents/PlugIns/obs-filters.so
            ./OBS.app/Contents/PlugIns/obs-transitions.so
            ./OBS.app/Contents/PlugIns/obs-vst.so
            ./OBS.app/Contents/PlugIns/rtmp-services.so
            ./OBS.app/Contents/MacOS/obs-ffmpeg-mux
            ./OBS.app/Contents/MacOS/obslua.so
            ./OBS.app/Contents/MacOS/_obspython.so
            ./OBS.app/Contents/PlugIns/obs-x264.so
            ./OBS.app/Contents/PlugIns/text-freetype2.so
            ./OBS.app/Contents/PlugIns/obs-outputs.so
          )

          if ! [ "${{ env.CEF_BUILD_VERSION_MAC }}" -le 3770 ]; then
          ../CI/scripts/macos/app/dylibBundler -cd -of -a ./OBS.app -q -f \
            -s ./OBS.app/Contents/MacOS \
            -s "${{ github.workspace }}/CI_BUILD/sparkle/Sparkle.framework" \
            -s ./rundir/RelWithDebInfo/bin \
            $(echo "${BUNDLE_PLUGINS[@]/#/-x }")
          else
          ../CI/scripts/macos/app/dylibBundler -cd -of -a ./OBS.app -q -f \
            -s ./OBS.app/Contents/MacOS \
            -s "${{ github.workspace }}/CI_BUILD/sparkle/Sparkle.framework" \
            -s ./rundir/RelWithDebInfo/bin \
            $(echo "${BUNDLE_PLUGINS[@]/#/-x }") \
            -x ./OBS.app/Contents/PlugIns/obs-browser-page
          fi

          mv ./libobs-opengl/libobs-opengl.so ./OBS.app/Contents/Frameworks

          cp -R /tmp/obsdeps/lib/QtNetwork.framework ./OBS.app/Contents/Frameworks
          chmod -R +w ./OBS.app/Contents/Frameworks/QtNetwork.framework
          rm -r ./OBS.app/Contents/Frameworks/QtNetwork.framework/Headers
          rm -r ./OBS.app/Contents/Frameworks/QtNetwork.framework/Versions/5/Headers/
          chmod 644 ./OBS.app/Contents/Frameworks/QtNetwork.framework/Versions/5/Resources/Info.plist
          install_name_tool -id @executable_path/../Frameworks/QtNetwork.framework/Versions/5/QtNetwork ./OBS.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
          install_name_tool -change /tmp/obsdeps/lib/QtCore.framework/Versions/5/QtCore @executable_path/../Frameworks/QtCore.framework/Versions/5/QtCore ./OBS.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork

          cp -R "${{ github.workspace }}/CI_BUILD/cef_binary_${{ env.CEF_BUILD_VERSION_MAC }}_macosx64/Release/Chromium Embedded Framework.framework" ./OBS.app/Contents/Frameworks/
          chown -R $(whoami) ./OBS.app/Contents/Frameworks/

          cp ../CI/scripts/macos/app/OBSPublicDSAKey.pem ./OBS.app/Contents/Resources

          if [ "${GITHUB_REF:0:10}" = "refs/tags/" ]; then
            plutil -insert CFBundleVersion -string ${{ env.OBS_GIT_TAG }}.0 ./OBS.app/Contents/Info.plist
            plutil -insert CFBundleShortVersionString -string ${{ env.OBS_GIT_TAG }} ./OBS.app/Contents/Info.plist
          else
            plutil -insert CFBundleVersion -string ${{ env.OBS_GIT_TAG }}.${{ env.GITHUB_RUN_NUMBER }} ./OBS.app/Contents/Info.plist
            plutil -insert CFBundleShortVersionString -string ${{ env.OBS_GIT_TAG }} ./OBS.app/Contents/Info.plist
          fi

          plutil -insert OBSFeedsURL -string https://obsproject.com/osx_update/feeds.xml ./OBS.app/Contents/Info.plist
          plutil -insert SUFeedURL -string https://obsproject.com/osx_update/stable/updates.xml ./OBS.app/Contents/Info.plist
          plutil -insert SUPublicDSAKeyFile -string OBSPublicDSAKey.pem ./OBS.app/Contents/Info.plist

          codesign --force --options runtime --sign "-" "./OBS.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/Autoupdate.app/Contents/MacOS/fileop"
          codesign --force --options runtime --sign "-" "./OBS.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/Autoupdate.app/Contents/MacOS/Autoupdate"
          codesign --force --options runtime --sign "-" --deep ./OBS.app/Contents/Frameworks/Sparkle.framework

          codesign --force --options runtime --entitlements "../CI/scripts/macos/app/entitlements.plist" --sign "-" "./OBS.app/Contents/Frameworks/Chromium Embedded Framework.framework/Libraries/libEGL.dylib"
          codesign --force --options runtime --entitlements "../CI/scripts/macos/app/entitlements.plist" --sign "-" "./OBS.app/Contents/Frameworks/Chromium Embedded Framework.framework/Libraries/libswiftshader_libEGL.dylib"
          codesign --force --options runtime --entitlements "../CI/scripts/macos/app/entitlements.plist" --sign "-" "./OBS.app/Contents/Frameworks/Chromium Embedded Framework.framework/Libraries/libGLESv2.dylib"
          codesign --force --options runtime --entitlements "../CI/scripts/macos/app/entitlements.plist" --sign "-" "./OBS.app/Contents/Frameworks/Chromium Embedded Framework.framework/Libraries/libswiftshader_libGLESv2.dylib"
          if ! [ "${{ env.CEF_BUILD_VERSION_MAC }}" -le 3770 ]; then
            codesign --force --options runtime --entitlements "../CI/scripts/macos/app/entitlements.plist" --sign "-" "./OBS.app/Contents/Frameworks/Chromium Embedded Framework.framework/Libraries/libvk_swiftshader.dylib"
          fi

          if ! [ "${{ env.CEF_BUILD_VERSION_MAC }}" -le 3770 ]; then
            codesign --force --options runtime --entitlements "../CI/scripts/macos/helpers/helper-entitlements.plist" --sign "-" --deep "./OBS.app/Contents/Frameworks/OBS Helper.app"
            codesign --force --options runtime --entitlements "../CI/scripts/macos/helpers/helper-gpu-entitlements.plist" --sign "-" --deep "./OBS.app/Contents/Frameworks/OBS Helper (GPU).app"
            codesign --force --options runtime --entitlements "../CI/scripts/macos/helpers/helper-plugin-entitlements.plist" --sign "-" --deep "./OBS.app/Contents/Frameworks/OBS Helper (Plugin).app"
            codesign --force --options runtime --entitlements "../CI/scripts/macos/helpers/helper-renderer-entitlements.plist" --sign "-" --deep "./OBS.app/Contents/Frameworks/OBS Helper (Renderer).app"
          fi

          codesign --force --options runtime --deep --sign "-" "./OBS.app/Contents/Resources/data/obs-mac-virtualcam.plugin"

          codesign --force --options runtime --entitlements "../CI/scripts/macos/app/entitlements.plist" --sign "-" --deep ./OBS.app

          codesign -dvv ./OBS.app


          FILE_DATE=$(date +%Y-%m-%d)
          FILE_NAME=$FILE_DATE-${{ env.OBS_GIT_HASH }}-${{ env.OBS_GIT_TAG }}-macOS.zip
          echo "FILE_NAME=${FILE_NAME}" >> $GITHUB_ENV
          zip -qr "${{ github.workspace }}/nightly/${FILE_NAME}" OBS.app

      - name: 'Upload build Artifact'
        if: success() && (github.event_name != 'pull_request' || env.SEEKING_TESTERS == '1')
        uses: actions/upload-artifact@v2.2.0
        with:
          name: 'obs-macos'
          path: ./nightly/*.zip

  002_linux_build:
    name: 'Linux (Ubuntu, 18.04)'
    runs-on: [ubuntu-18.04]
    needs: [001_clang_check]
    defaults:
      run:
        shell: bash
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.3
        with:
          submodules: 'recursive'

      - name: 'Check for Github Labels'
        if: github.event_name == 'pull_request'
        run: |
          LABELS_URL="$(echo ${{ github.event.pull_request.url }} | sed s'/pulls/issues/')"
          LABEL_FOUND="$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "${LABELS_URL}/labels" | sed -n 's/.*"name": "\(.*\)",/\1/p' | grep 'Seeking Testers' || true)"
          if [ "${LABEL_FOUND}" = "Seeking Testers" ]; then
            echo "SEEKING_TESTERS=1" >> $GITHUB_ENV
          else
            echo "SEEKING_TESTERS=0" >> $GITHUB_ENV
          fi
      - name: 'Setup build environment'
        run: |
          git fetch --prune --unshallow
          echo "OBS_GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          echo "OBS_GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "OBS_GIT_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

          echo "NPROC=$(($(nproc)+1))" >> $GITHUB_ENV

          sudo dpkg --add-architecture amd64
          sudo apt-get -qq update
          sudo apt-get install -y \
           build-essential \
           checkinstall \
           cmake \
           libasound2-dev \
           libavcodec-dev \
           libavdevice-dev \
           libavfilter-dev \
           libavformat-dev \
           libavutil-dev \
           libcurl4-openssl-dev \
           libfdk-aac-dev \
           libfontconfig-dev \
           libfreetype6-dev \
           libgl1-mesa-dev \
           libjack-jackd2-dev \
           libjansson-dev \
           libluajit-5.1-dev \
           libpulse-dev \
           libqt5x11extras5-dev \
           libsndio-dev \
           libspeexdsp-dev \
           libswresample-dev \
           libswscale-dev \
           libudev-dev \
           libv4l-dev \
           libva-dev \
           libvlc-dev \
           libx11-dev \
           libx264-dev \
           libxcb-randr0-dev \
           libxcb-shm0-dev \
           libxcb-xinerama0-dev \
           libxcomposite-dev \
           libxinerama-dev \
           libmbedtls-dev \
           pkg-config \
           python3-dev \
           qtbase5-dev \
           qtbase5-private-dev \
           libqt5svg5-dev \
           swig \
           libcmocka-dev \
           linux-generic \
           v4l2loopback-dkms

           mkdir ${{ github.workspace }}/build
           mkdir ${{ github.workspace }}/nightly

      - name: 'Restore Chromium Embedded Framework from cache'
        id: cef-cache
        uses: actions/cache@v2.1.2
        env:
          CACHE_NAME: 'cef-cache'
        with:
          path: ${{ github.workspace }}/CI_BUILD/cef_binary_${{ env.CEF_BUILD_VERSION_LINUX }}_linux64
          key: ${{ runner.os }}-pr-${{ env.CACHE_NAME }}-${{ env.CEF_BUILD_VERSION_LINUX }}

      - name: 'Install prerequisite: Chromium Embedded Framework'
        if: steps.cef-cache.outputs.cache-hit != 'true'
        run: |
          curl -kL https://cdn-fastly.obsproject.com/downloads/cef_binary_${{ env.CEF_BUILD_VERSION_LINUX }}_linux64.tar.bz2 -f --retry 5 -o cef.tar.bz2
          if [ ! -d "${{ github.workspace }}/CI_BUILD" ]; then mkdir "${{ github.workspace }}/CI_BUILD"; fi
          tar -C"${{ github.workspace }}/CI_BUILD" -xjf cef.tar.bz2

      - name: 'Build OBS'
        working-directory: '${{ github.workspace }}/build'
        run: |
          cmake -DUNIX_STRUCTURE=0 -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/obs-studio-portable" -DENABLE_UNIT_TESTS=ON -DENABLE_VLC=ON -DWITH_RTMPS=ON -DBUILD_BROWSER=ON -DCEF_ROOT_DIR="${{ github.workspace }}/CI_BUILD/cef_binary_${{ env.CEF_BUILD_VERSION_LINUX }}_linux64" -DTWITCH_CLIENTID='${{ env.TWITCH_CLIENTID }}' -DTWITCH_HASH='${{ env.TWITCH_HASH }}' -DRESTREAM_CLIENTID='${{ env.RESTREAM_CLIENTID }}' -DRESTREAM_HASH='${{ env.RESTREAM_HASH }}' ..

          make -j${NPROC:-4}

      - name: 'Run tests'
        if: success()
        working-directory: ${{ github.workspace }}/build
        run: make CTEST_OUTPUT_ON_FAILURE=1 test

      - name: 'Archive build artifact'
        if: success() && (github.event_name != 'pull_request' || env.SEEKING_TESTERS == '1')
        run: |
          FILE_DATE=$(date +%Y-%m-%d)
          FILE_NAME=$FILE_DATE-${{ env.OBS_GIT_HASH }}-${{ env.OBS_GIT_TAG }}-linux64.tar.gz
          echo "FILE_NAME=${FILE_NAME}" >> $GITHUB_ENV

          sudo checkinstall --default --install=no --pkgname=obs-studio --fstrans=yes --backup=no --pkgversion="$(date +%Y%m%d)-git" --deldoc=yes
          tar -cvzf "${{ github.workspace }}/nightly/${FILE_NAME}" *.deb

      - name: 'Upload build artifact'
        if: success() && (github.event_name != 'pull_request' || env.SEEKING_TESTERS == '1')
        uses: actions/upload-artifact@2.2.0
        with:
          name: 'obs-linux'
          path: ./nightly/*.tar.gz

  002_windows_build:
    name: 'Windows (Latest, 64bit+32bit)'
    runs-on: [windows-latest]
    needs: [001_clang_check]
    strategy:
      matrix:
        win_arch: [64, 32]
    env:
      CMAKE_GENERATOR: "Visual Studio 16 2019"
      CMAKE_SYSTEM_VERSION: "10.0.18363.657"
      VIRTUALCAM-GUID: "A3FCE0F5-3493-419F-958A-ABA1250EC20B"
    steps:
      - name: 'Add msbuild to PATH'
        uses: microsoft/setup-msbuild@v1.0.2

      - name: 'Checkout'
        uses: actions/checkout@v2.3.3
        with:
          submodules: 'recursive'

      - name: 'Check for Github Labels'
        if: github.event_name == 'pull_request'
        shell: bash
        run: |
          LABELS_URL="$(echo ${{ github.event.pull_request.url }} | sed s'/pulls/issues/')"
          LABEL_FOUND="$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "${LABELS_URL}/labels" | sed -n 's/.*"name": "\(.*\)",/\1/p' | grep 'Seeking Testers' || true)"
          if [ "${LABEL_FOUND}" = "Seeking Testers" ]; then
            echo "SEEKING_TESTERS=1" >> $GITHUB_ENV
          else
            echo "SEEKING_TESTERS=0" >> $GITHUB_ENV
          fi

      - name: 'Setup build environment'
        shell: bash
        run: |
          git fetch --prune --unshallow
          echo "OBS_GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          echo "OBS_GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "OBS_GIT_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

          mkdir ${{ github.workspace }}/build
          mkdir ${{ github.workspace }}/nightly

      - name: 'Restore VLC dependency from cache'
        id: vlc-cache
        uses: actions/cache@v2.1.2
        env:
          CACHE_NAME: 'windows-vlc-cache'
        with:
          path: ${{ github.workspace }}/CI_BUILD/vlc
          key: ${{ runner.os }}-pr-${{ env.CACHE_NAME }}-${{ env.VLC_VERSION }}

      - name: 'Install dependencies'
        env:
          INSTALL_VLC: ${{ !steps.vlc-cache.outputs.cache-hit }}
        run: |
          echo "  + Installing dependencies v${{ env.DEPS_VERSION_WIN }}"
          curl -kLO https://cdn-fastly.obsproject.com/downloads/dependencies${{ env.DEPS_VERSION_WIN }}.zip -f --retry 5 -C -
          7z x dependencies${{ env.DEPS_VERSION_WIN }}.zip -o"${{ github.workspace }}/CI_BUILD/deps"

          echo "  + Installing Qt v${{ env.QT_VERSION_WIN }}"
          curl -kLO https://cdn-fastly.obsproject.com/downloads/Qt_${{ env.QT_VERSION_WIN }}.7z -f --retry 5 -C -
          7z x Qt_${{ env.QT_VERSION_WIN }}.7z -o"${{ github.workspace }}/CI_BUILD/QT"

          echo "  + Installing Chromium Embedded Framework (CEF) v${{ env.CEF_BUILD_VERSION_WIN }}"
          curl -kL https://cdn-fastly.obsproject.com/downloads/cef_binary_${{ env.CEF_VERSION }}_windows64_minimal.zip -f --retry 5 -o cef.zip
          7z x cef.zip -o"${{ github.workspace }}/CI_BUILD"

          if ($env:INSTALL_VLC -eq "true") {
            echo "  + Installing VLC v${{ env.VLC_VERSION_WIN }}"
            curl -kL https://cdn-fastly.obsproject.com/downloads/vlc.zip -f --retry 5 -o vlc.zip
            7z x vlc.zip -o"${{ github.workspace }}/CI_BUILD/vlc"
          }

          mkdir ${{ github.workspace }}/build
          mkdir ${{ github.workspace }}/build${{ matrix.win_arch }}
          mkdir ${{ github.workspace }}/nightly

      - name: 'Build OBS'
        working-directory: '${{ github.workspace }}/build${{ matrix.win_arch }}'
        run: |
          if ("${{ matrix.win_arch" -eq "64") {
            $env:BUILD_ARCH="x64"
          } else {
            $env:BUILD_ARCH="Win32"
          }
          cmake -G"${{ env.CMAKE_GENERATOR }}" \
            -A"$env:BUILD_ARCH" \
            -DCMAKE_SYSTEM_VERSION="${{ env.CMAKE_SYSTEM_VERSION }}" \
            -DBUILD_BROWSER=ON \
            -DCOMPILE_D3D12_HOOK=ON \
            -DVLCPath="${{ github.workspace }}/CI_BUILD/vlc" \
            -DDepsPath="${{ github.workspace }}/CI_BUILD/deps/win${{ matrix.win_arch }}" \
            -DQTDIR="${{ github.workspace }}/CI_BUILD/QT/${{ env.QT_VERSION }}/msvc2019_${{ matrix.win_arch }}" \
            -DENABLE_VLC=ON \
            -DCEF_ROOT_DIR="${{ github.workspace }}/CI_BUILD/cef_binary_${{ env.CEF_VERSION }}_windows${{ matrix.win_arch }}_minimal" \
            -DTWITCH_CLIENTID='${{ env.TWITCH_CLIENTID }}' \
            -DTWITCH_HASH='${{ env.TWITCH_HASH }}' \
            -DRESTREAM_CLIENTID='${{ env.RESTREAM_CLIENTID }}' \
            -DRESTREAM_HASH='${{ env.RESTREAM_HASH }}' \
            -DCOPIED_DEPENDENCIES=FALSE \
            -DCOPY_DEPENDENCIES=TRUE \
            -DVIRTUALCAM_GUID=${{ env.VIRTUALCAM-GUID }} \
            ..

          msbuild /m /p:Configuration=RelWithDebInfo .\obs-studio.sln

      - name: 'Create build artifact'
        if: success() && (github.event_name != 'pull_request' || env.SEEKING_TESTERS == '1')
        run: |
          $env:FILE_DATE=(Get-Date -UFormat "%F")
          $env:FILE_NAME="${env:FILE_DATE}-${{ env.OBS_GIT_HASH }}-${{ env.OBS_GIT_TAG }}-win${{ matrix.win_arch }}.zip"
          echo "FILE_NAME=${env:FILE_NAME}" >> ${env:GITHUB_ENV}
          robocopy .\build${{ matrix.win_arch }}\rundir\RelWithDebInfo .\build\ /E /XF .gitignore
          7z a ${env:FILE_NAME} .\build\*

      - name: 'Upload build artifact'
        if: success() && (github.event_name != 'pull_request' || env.SEEKING_TESTERS == '1')
        uses: actions/upload-artifact@v2.2.0
        with:
          name: 'obs-win${{ matrix.win_arch }}'
          path: '*-win${{ matrix.win_arch }}.zip'

  003_macos_package:
    name: 'Create macOS disk image'
    runs-on: [macos-latest]
    needs: [002_macos_build]
    defaults:
      run:
        shell: bash
    steps:
      - name: 'Download artifact'
        id: artifact_download
        uses: actions/download-artifact@v2
        continue-on-error: true
        with:
          name: 'obs-macos'

      - name: 'Install prerequisite DMGbuild'
        if: steps.artifact_download.outcome != 'failure'
        run: pip3 install dmgbuild

      - name: 'Create disk image for distribution'
        if: steps.artifact_download.outcome != 'failure'
        run: |
          FILE_DATE=$(date +%Y-%m-%d)
          FILE_NAME=$FILE_DATE-${{ env.OBS_GIT_HASH }}-${{ env.OBS_GIT_TAG }}-macOS.dmg
          echo "FILE_NAME=${FILE_NAME}" >> $GITHUB_ENV

          curl -o './settings.json' https://raw.githubusercontent.com/obsproject/obs-studio/${{ github.sha }}/CI/scripts/macos/package/settings.json.template
          /usr/bin/sed -i '' 's#\$\$VERSION\$\$#${{ env.OBS_GIT_TAG }}#g' ./settings.json
          /usr/bin/sed -i '' 's#\$\$CI_PATH\$\$#../CI/scripts/macos#g' ./settings.json
          /usr/bin/sed -i '' 's#\$\$BUNDLE_PATH\$\$#${{ github.workspace }}/build#g' ./settings.json

          dmgbuild "OBS-Studio ${{ env.OBS_GIT_TAG }}" "${FILE_NAME}" -s ./settings.json
          codesign --force --sign "${{ secrets.MACOS_SIGNING_IDENTITY }} }}" ./"${FILE_NAME}"
          codesign -dvv ./"${FILE_NAME}"

      - name: 'Publish macOS disk image'
        if: steps.artifact_download.outcome != 'failure'
        uses: actions/upload-artifact@v2.2.0
        with:
          name: 'obs-macos-nightly'
          path: ./*.dmg

  003_linux_package:
    name: 'Create Linux Flatpack Bundle'
    runs-on: [ubuntu-latest]
    needs: [002_linux_build]
    if: startsWith(github.ref, 'refs/tags/') && github.event_name != 'pull_request'
    defaults:
      run:
        shell: bash
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-5.15
      options: --privileged
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2.3.3
      with:
        submodules: 'recursive'

    - name: Build Flatpak Manifest
      uses: bilelmoussaoui/flatpak-github-actions@v2
      with:
        bundle: obs-studio-${{ github.sha }}.flatpak
        manifest-path: CI/flatpak/com.obsproject.Studio.json

  003_windows_package:
    name: 'Create Windows Installer'
    runs-on: [ubuntu-latest]
    needs: [002_windows_build]
    if: startsWith(github.ref, 'refs/tags/') && github.event_name != 'pull_request'
    steps:
      - name: 'Download 64-bit artifact'
        uses: actions/download-artifact@v2
        with:
          name: 'obs-win64'
          path: ${{ github.workspace }}/win64/

      - name: 'Download 32-bit artifact'
        uses: actions/download-artifact@v2
        with:
          name: 'obs-win32'
          path: ${{ github.workspace }}/win32/

      - name: 'Do nothing for now'
        run: echo "Under construction"

  004_macos_release:
    name: 'Create macOS disk image'
    runs-on: [macos-latest]
    needs: [002_macos_build]
    if: startsWith(github.ref, 'refs/tags/') && github.event_name != 'pull_request' && secrets.MACOS_SIGNING_IDENTITY != null
    defaults:
      run:
        shell: bash
    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v2
        with:
          name: 'obs-macos'

      - name: 'Install Apple Developer Certificate'
        uses: apple-actions/import-codesign-certs@253ddeeac23f2bdad1646faac5c8c2832e800071
        with:
          p12-file-base64: ${{ secrets.MACOS_SIGNING_CERT }}
          p12-password: ${{ secrets.MACOS_SIGNING_CERT_PASSWORD }}

      - name: 'Install prerequisite DMGbuild'
        run: pip3 install dmgbuild

      - name: 'Code signing macOS app bundle'
        run: |
          codesign --force --options runtime --sign "${{ secrets.MACOS_SIGNING_IDENTITY }}" "./OBS.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/Autoupdate.app/Contents/MacOS/fileop"
          codesign --force --options runtime --sign "${{ secrets.MACOS_SIGNING_IDENTITY }}" "./OBS.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/Autoupdate.app/Contents/MacOS/Autoupdate"
          codesign --force --options runtime --sign "${{ secrets.MACOS_SIGNING_IDENTITY }}" --deep ./OBS.app/Contents/Frameworks/Sparkle.framework

          codesign --force --options runtime --entitlements "../CI/scripts/macos/app/entitlements.plist" --sign "${{ secrets.MACOS_SIGNING_IDENTITY }}" "./OBS.app/Contents/Frameworks/Chromium Embedded Framework.framework/Libraries/libEGL.dylib"
          codesign --force --options runtime --entitlements "../CI/scripts/macos/app/entitlements.plist" --sign "${{ secrets.MACOS_SIGNING_IDENTITY }}" "./OBS.app/Contents/Frameworks/Chromium Embedded Framework.framework/Libraries/libswiftshader_libEGL.dylib"
          codesign --force --options runtime --entitlements "../CI/scripts/macos/app/entitlements.plist" --sign "${{ secrets.MACOS_SIGNING_IDENTITY }}" "./OBS.app/Contents/Frameworks/Chromium Embedded Framework.framework/Libraries/libGLESv2.dylib"
          codesign --force --options runtime --entitlements "../CI/scripts/macos/app/entitlements.plist" --sign "${{ secrets.MACOS_SIGNING_IDENTITY }}" "./OBS.app/Contents/Frameworks/Chromium Embedded Framework.framework/Libraries/libswiftshader_libGLESv2.dylib"
          if ! [ "${{ env.CEF_BUILD_VERSION_MAC }}" -le 3770 ]; then
            codesign --force --options runtime --entitlements "../CI/scripts/macos/app/entitlements.plist" --sign "${{ secrets.MACOS_SIGNING_IDENTITY }}" "./OBS.app/Contents/Frameworks/Chromium Embedded Framework.framework/Libraries/libvk_swiftshader.dylib"
          fi

          if ! [ "${{ env.CEF_BUILD_VERSION_MAC }}" -le 3770 ]; then
            codesign --force --options runtime --entitlements "../CI/scripts/macos/helpers/helper-entitlements.plist" --sign "${{ secrets.MACOS_SIGNING_IDENTITY }}" --deep "./OBS.app/Contents/Frameworks/OBS Helper.app"
            codesign --force --options runtime --entitlements "../CI/scripts/macos/helpers/helper-gpu-entitlements.plist" --sign "${{ secrets.MACOS_SIGNING_IDENTITY }}" --deep "./OBS.app/Contents/Frameworks/OBS Helper (GPU).app"
            codesign --force --options runtime --entitlements "../CI/scripts/macos/helpers/helper-plugin-entitlements.plist" --sign "${{ secrets.MACOS_SIGNING_IDENTITY }}" --deep "./OBS.app/Contents/Frameworks/OBS Helper (Plugin).app"
            codesign --force --options runtime --entitlements "../CI/scripts/macos/helpers/helper-renderer-entitlements.plist" --sign "${{ secrets.MACOS_SIGNING_IDENTITY }}" --deep "./OBS.app/Contents/Frameworks/OBS Helper (Renderer).app"
          fi

          codesign --force --options runtime --deep --sign "${{ secrets.MACOS_SIGNING_IDENTITY }}" "./OBS.app/Contents/Resources/data/obs-mac-virtualcam.plugin"

          codesign --force --options runtime --entitlements "../CI/scripts/macos/app/entitlements.plist" --sign "${{ secrets.MACOS_SIGNING_IDENTITY }}" --deep ./OBS.app

          codesign -dvv ./OBS.app

      - name: 'Create disk image for distribution'
        run: |
          FILE_DATE=$(date +%Y-%m-%d)
          FILE_NAME=$FILE_DATE-${{ env.OBS_GIT_HASH }}-${{ env.OBS_GIT_TAG }}-macOS.dmg
          echo "FILE_NAME=${FILE_NAME}" >> $GITHUB_ENV

          curl -o './settings.json' https://raw.githubusercontent.com/obsproject/obs-studio/${GITHUB_REF#refs/*/}/CI/scripts/macos/package/settings.json.template
          /usr/bin/sed -i '' 's#\$\$VERSION\$\$#${{ env.OBS_GIT_TAG }}#g' ./settings.json
          /usr/bin/sed -i '' 's#\$\$CI_PATH\$\$#../CI/scripts/macos#g' ./settings.json
          /usr/bin/sed -i '' 's#\$\$BUNDLE_PATH\$\$#${{ github.workspace }}/build#g' ./settings.json

          dmgbuild "OBS-Studio ${{ env.OBS_GIT_TAG }}" "${FILE_NAME}" -s ./settings.json
          codesign --force --sign "${{ secrets.MACOS_SIGNING_IDENTITY }} }}" ./"${FILE_NAME}"
          codesign -dvv ./"${FILE_NAME}"

          xcrun altool --store-password-in-keychain-item "AC_PASSWORD" -u "${{ secrets.MACOS_NOTARIZATION_USERNAME }}" -p "${{ secrets.MACOS_NOTARIZATION_PASSWORD }}"

          xcnotary precheck "./OBS.app"

          if [ "$?" -eq 0 ]; then
            xcnotary notarize "$FILE_NAME" --developer-account "${{ secrets.MACOS_NOTARIZATION_USERNAME }}" --developer-password-keychain-item "AC_PASSWORD" --provider "${{ secrets.ASC_PROVIDER_SHORTNAME }}"
          else
            return 1
          fi

      - name: 'Publish macOS disk image'
        uses: actions/upload-artifact@v2.2.0
        with:
          name: 'obs-macos-release'
          path: ./*.dmg
