name: Publish Release Builds 📡
on:
  workflow_call:
    inputs:
      flatpakMatrix:
        description: Flatpak Release Matrix
        required: true
        type: string
jobs:
  flatpak-publish:
    name: Publish to Flathub 📦
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    env:
      FLATPAK_BUILD_PATH: flatpak_app/files/share
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-6.4
      options: --privileged
    strategy:
      matrix:
        branch: ${{ fromJSON(inputs.flatpakMatrix) }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup Environment 🔧
        id: setup
        run: |
          ## SETUP ENVIRONMENT SCRIPT
          echo "commitHash=$(git rev-parse --short=9 HEAD)" >> $GITHUB_OUTPUT
          git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Build Flatpak Manifest
        uses: flatpak/flatpak-github-actions/flatpak-builder@v5
        with:
          bundle: obs-studio-${{ steps.setup.outputs.commitHash }}.flatpak
          manifest-path: ./.github/scripts/utils.flatpak/com.obsproject.Studio.json
          cache-key: flatpak-builder-${{ hashFiles('./.github/scripts/utils.flatpak/com.obsproject.Studio.json') }}
          mirror-screenshots-url: https://dl.flathub.org/repo/screenshots
          branch: ${{ matrix.branch }}
      - name: Validate AppStream
        working-directory: ${{ env.FLATPAK_BUILD_PATH }}
        run: appstream-util validate appdata/com.obsproject.Studio.appdata.xml
      - name: Verify Icon and Metadata in app-info
        working-directory: ${{ env.FLATPAK_BUILD_PATH }}
        run: |
          test -f app-info/icons/flatpak/128x128/com.obsproject.Studio.png || { echo "Missing 128x128 icon in app-info!"; exit 1; }
          test -f app-info/xmls/com.obsproject.Studio.xml.gz || { echo "Missing com.obsproject.Studio.xml.gz in app-info!"; exit 1; }
      - name: Commit Screenshots to OSTree Repository
        run: ostree commit --repo=repo --canonical-permissions --branch=screenshots/x86_64 flatpak_app/screenshots
      - name: Publish to Flathub Beta
        uses: flatpak/flatpak-github-actions/flat-manager@v5
        if: ${{ matrix.branch == 'beta' }}
        with:
          flat-manager-url: https://hub.flathub.org/
          repository: beta
          token: ${{ secrets.FLATHUB_BETA_TOKEN }}
      - name: Publish to Flathub
        uses: flatpak/flatpak-github-actions/flat-manager@v5
        if: ${{ matrix.branch == 'stable' }}
        with:
          flat-manager-url: https://hub.flathub.org/
          repository: stable
          token: ${{ secrets.FLATHUB_TOKEN }}
  steam-upload:
    name: Upload Steam builds 🚂
    #if: ${{ github.repository_owner == 'obsproject' }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          path: source
      - uses: ./.github/actions/steam-upload
        with:
          steamSecret: ${{ secrets.STEAM_SHARED_SECRET }}
          steamUser: ${{ secrets.STEAM_USER }}
          steamPassword: ${{ secrets.STEAM_PASSWORD }}
          workflowSecret: ${{ secrets.GITHUB_TOKEN }}
          sourcePath: ${{ github.workspace }}/source
          preview: 'true'
