name: Push Tag
run-name: Push Tag - ${{ github.ref_name }}
on:
  push:
    paths-ignore:
      - '**.md'
    tags:
      - '*'
permissions:
  contents: read    # Necessary for repository checkouts.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash --noprofile --norc -eo errexit -eo pipefail -eo nounset {0}
jobs:
  build-project:
    name: Build
    uses: ./.github/workflows/build-project.yaml
    secrets:
      macos-signing-identity: ${{ secrets.MACOS_SIGNING_IDENTITY }}
      macos-signing-certificate: ${{ secrets.MACOS_SIGNING_CERT }}
      macos-signing-password: ${{ secrets.MACOS_SIGNING_CERT_PASSWORD }}
      macos-provisioning-profile: ${{ secrets.MACOS_SIGNING_PROVISIONING_PROFILE }}
      macos-notarization-user: ${{ secrets.MACOS_NOTARIZATION_USERNAME }}
      macos-notarization-password: ${{ secrets.MACOS_NOTARIZATION_PASSWORD }}
      restream-client-id: ${{ secrets.RESTREAM_CLIENTID }}
      restream-hash: ${{ secrets.RESTREAM_HASH }}
      twitch-client-id: ${{ secrets.TWITCH_CLIENT_ID }}
      twitch-hash: ${{ secrets.TWITCH_HASH }}
      youtube-client-id: ${{ secrets.YOUTUBE_CLIENTID }}
      youtube-client-hash: ${{ secrets.YOUTUBE_CLIENTID_HASH }}
      yotube-client-secret: ${{ secrets.YOUTUBE_SECRET }}
      yotube-client-secret-hash: ${{ secrets.YOUTUBE_SECRET_HASH }}
      gpu-priority-val: ${{ secrets.GPU_PRIORITY_VAL }}

  update-documentation:
    name: Update Documentation
    if: fromJSON(vars.ENABLE_DOCUMENTATION_UPDATE || 'false')
    runs-on: ubuntu-26.04
    outputs:
      artifact-name: ${{ steps.generate.outputs.artifact-name }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Check for Changed Files
        uses: ./.github/actions/check-changes
        id: checks
        with:
          base: ${{ github.event.before }}
          pathspec: ':!cmake* :!*CMakeLists.txt'

      - name: Generate Documentation
        uses: ./.github/actions/generate-docs
        id: generate
        with:
          disable-link-extensions: true

  deploy-documentation:
    name: Deploy Documentation To Cloudflare
    if: |-
      fromJSON(vars.ENABLE_DOCUMENTATION_UPDATE || 'false')
      && vars.CF_PAGES_PROJECT != ''
    runs-on: ubuntu-26.04
    needs: update-documentation
    environment:
      name: cf-pages-deploy
      deployment: false
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ needs.update-documentation.outputs.artifact-name }}
          path: docs

      - name: Set Up Redirects
        env:
          CF_PAGES_PROJECT: ${{ vars.CF_PAGES_PROJECT }}
        run: |
          : Set Up Redirects
          if [[ -n "${RUNNER_DEBUG:-}" ]]; then set -x; fi
          {
            echo "/previous/27.2 https://obsproject.com/docs/27.2 302"
            echo "/previous/:major.:minor https://:major-:minor.${CF_PAGES_PROJECT}.pages.dev 302"
          } >> "${GITHUB_WORKSPACE}/docs/_redirects"

      - name: Publish To Live Page
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          workingDirectory: ${{ github.workspace }}/docs
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: |-
            pages publish ${{ github.workspace }}/docs
            --project-name=${{ vars.CF_PAGES_PROJECT }}
            --commit-hash=${{ github.sha }}

  sign-windows-build:
    name: Windows Signing
    uses: patthemav/obs-studio/.github/workflows/sign-windows.yaml@ac19ea663375cd02997be92b7d8ff6dd89a511ad
    if: |-
      github.repository_owner == 'obsproject' &&
      fromJSON(vars.ENABLE_WINDOWS_CODE_SIGNING || 'false')
    needs: build-project
    permissions:
      contents: read        # Necessary to keep workflow base permissions.
      attestations: write   # Necessary to generate an attestation for the code signed build.
    secrets:
      gcp-identity-pool: ${{ secrets.GCP_IDENTITY_POOL }}
      gcp-service-account-name: ${{ secrets.GCP_SERVICE_ACCOUNT_NAME }}

  # create-release:
  #   name: Create Release
  #   if: github.ref_type == 'tag'
  #   runs-on: ubuntu-26.04
  #   needs: [build-project, sign-windows-build]
  #   permissions:
  #     contents: read
  #   steps:
  #     - name: Check Release Tag
  #       id: check
  #       run: |
  #         : Check Release Tag
  #         if [[ -n "${RUNNER_DEBUG:-}" ]]; then set -x; fi
  #         shopt -s extglob

  #         case "${GITHUB_REF_NAME}" in
  #           +([0-9]).+([0-9]).+([0-9]) )
  #             echo 'validTag=true' >> "${GITHUB_OUTPUT}"
  #             echo 'prerelease=false' >> "${GITHUB_OUTPUT}"
  #             echo "version=${GITHUB_REF_NAME}" >> "${GITHUB_OUTPUT}"
  #             ;;
  #           +([0-9]).+([0-9]).+([0-9])-@(beta|rc)*([0-9]) )
  #             echo 'validTag=true' >> "${GITHUB_OUTPUT}"
  #             echo 'prerelease=true' >> "${GITHUB_OUTPUT}"
  #             echo "version=${GITHUB_REF_NAME}" >> "${GITHUB_OUTPUT}"
  #             ;;
  #           *)
  #             echo 'validTag=false' >> "${GITHUB_OUTPUT}"
  #             ;;
  #         esac

  #     - name: Download Build Artifacts
  #       uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
  #       if: ${{ fromJSON(steps.check.outputs.validTag) }}

  #     - name: Rename Files
  #       if: fromJSON(steps.check.outputs.validTag)
  #       env:
  #         RELEASE_VERSION: ${{ steps.check.outputs.version }}
  #       run: |
  #         : Rename Files
  #         if [[ -n "${RUNNER_DEBUG:-}" ]]; then set -x; fi

  #         shopt -s extglob

  #         local commit_hash="${GITHUB_SHA:0:9}"
  #         local -A platform_names=(
  #           [macos-arm64]=macOS-Apple.dmg
  #           [macos-arm64-debug-symbols]=macOS-Apple-dSYMs.tar.xz
  #           [macos-arm64-dev]=macOS-Apple-Libraries.tar.xz
  #           [macos-x86_64]=macOS-Intel.dmg
  #           [macos-x86_64-debug-symbols]=macOS-Intel-dSYMs.tar.xz
  #           [macos-x86_64-dev]=macOS-Intel-Libraries.tar.xz
  #           [ubuntu-24.04-x86_64]=Ubuntu-24.04-x86_64.deb
  #           [ubuntu-24.04-x86_64-debug-symbols]=Ubuntu-24.04-x86_64-dbsym.ddeb
  #           [ubuntu-24.04-x86_64-sources]=Ubuntu-24.04-x86_64-Sources.tar.gz
  #           [ubuntu-26.04-x86_64]=Ubuntu-26.04-x86_64.deb
  #           [ubuntu-26.04-x86_64-debug-symbols]=Ubuntu-26.04-x86_64-dbsym.ddeb
  #           [windows-x64]=Windows-x64.zip
  #           [windows-x64-installer]=Windows-x64-Installer.exe
  #           [windows-x64-debug-symbols]=Windows-x64-PDBs.zip
  #           [windows-arm64]=Windows-ARM64.zip
  #           [windows-arm64-debug-symbols]=Windows-ARM64-PDBs.zip
  #         )

  #         local platform_glob="@(macos|windows|ubuntu-*)-@(arm64|x86_64|x64)"
  #         local extension_glob="@(dmg|tar.xz|zip|exe|deb|ddeb)"
  #         local glob_expression="obs-studio-${platform_glob}-${commit_hash}*.${extension_glob}"
  #         local -a downloaded_files=("${GITHUB_WORKSPACE}"/${glob_expression})

  #         local platform
  #         local output_name
  #         local -a release_files=()
  #         for file in "${downloaded_files[@]}"; do
  #           platform="${file//obs-studio-}"
  #           platform="${platform//"-${commit_hash}"}"

  #           output_name="OBS-Studio-${RELEASE_VERSION}-${platform_names["${platform}"]}"

  #           release_files+=("${output_name}")

  #           mv "${GITHUB_WORKSPACE}/${file}" "${GITHUB_WORKSPACE}/${output_name}"
  #         done

  #     - name: Generate Release List And Checksums
  #       if: fromJSON(steps.check.outputs.validTag)
  #       id: checksums
  #       run: |
  #         : Generate Release List And Checksums
  #         if [[ -n "${RUNNER_DEBUG:-}" ]]; then set -x; fi
  #         shopt -s extglob

  #         local -a release_files=()
  #         local shasum_output
  #         local checksum

  #         echo "### Checksums" > "${GITHUB_WORKSPACE}/CHECKSUMS.txt"
  #         for file in "${GITHUB_WORKSPACE}/"@(*.deb|*.ddeb|*.dmg|*.tar.xz|*.tar.gz|*.exe|*.zip); do
  #           shasum_output="$(shasum --algorithm=256 "${file}")"
  #           read -r checksum _ <<< "${shasum_output}"
  #           echo "    ${file##*/}: ${checksum}" >> "${GITHUB_WORKSPACE}/CHECKSUMS.txt"

  #           release_files+=("${file}")
  #         done

  #         local file_list="$(printf '%s\n' "${release_files[@]}")"

  #         {
  #           echo "checksumFile=${GITHUB_WORKSPACE}/CHECKSUMS.txt"
  #           echo 'releaseFiles<<EOF'
  #           echo "${file_list}"
  #           echo EOF
  #         } >> "${GITHUB_OUTPUT}"

  #     - name: Create Release
  #       if: fromJSON(steps.check.outputs.validTag)
  #       id: create_release
  #       uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
  #       with:
  #         draft: true
  #         prerelease: ${{ fromJSON(steps.check.outputs.prerelease) }}
  #         tag_name: ${{ steps.check.outputs.version }}
  #         name: OBS Studio ${{ steps.check.outputs.version }}
  #         body_path: ${{ github.workspace }}/CHECKSUMS.txt
  #         files: ${{ steps.checksums.outputs.releaseFiles }}
