name: Push Tag
run-name: Push Tag - ${{ github.ref_name }}
on:
  push:
    paths-ignore:
      - '**.md'
    tags:
      - '*'
permissions:
  contents: read    # Necessary for repository checkouts.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash --noprofile --norc -eo errexit -eo pipefail -eo nounset {0}
jobs:
  build-project:
    name: Build
    uses: ./.github/workflows/build-project.yaml
    secrets:
      macos-signing-identity: ${{ secrets.MACOS_SIGNING_IDENTITY }}
      macos-signing-certificate: ${{ secrets.MACOS_SIGNING_CERT }}
      macos-signing-password: ${{ secrets.MACOS_SIGNING_CERT_PASSWORD }}
      macos-provisioning-profile: ${{ secrets.MACOS_SIGNING_PROVISIONING_PROFILE }}
      macos-notarization-user: ${{ secrets.MACOS_NOTARIZATION_USERNAME }}
      macos-notarization-password: ${{ secrets.MACOS_NOTARIZATION_PASSWORD }}
      restream-client-id: ${{ secrets.RESTREAM_CLIENTID }}
      restream-hash: ${{ secrets.RESTREAM_HASH }}
      twitch-client-id: ${{ secrets.TWITCH_CLIENT_ID }}
      twitch-hash: ${{ secrets.TWITCH_HASH }}
      youtube-client-id: ${{ secrets.YOUTUBE_CLIENTID }}
      youtube-client-hash: ${{ secrets.YOUTUBE_CLIENTID_HASH }}
      yotube-client-secret: ${{ secrets.YOUTUBE_SECRET }}
      yotube-client-secret-hash: ${{ secrets.YOUTUBE_SECRET_HASH }}
      gpu-priority-val: ${{ secrets.GPU_PRIORITY_VAL }}

  update-documentation:
    name: Update Documentation
    if: fromJSON(vars.ENABLE_DOCUMENTATION_UPDATE || 'false')
    runs-on: ubuntu-26.04
    outputs:
      artifact-name: ${{ steps.generate.outputs.artifact-name }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Check for Changed Files
        uses: ./.github/actions/check-changes
        id: checks
        with:
          base: ${{ github.event.before }}
          pathspec: ':!cmake* :!*CMakeLists.txt'

      - name: Generate Documentation
        uses: ./.github/actions/generate-docs
        id: generate
        with:
          disable-link-extensions: true

  deploy-documentation:
    name: Deploy Documentation To Cloudflare
    if: |-
      fromJSON(vars.ENABLE_DOCUMENTATION_UPDATE || 'false')
      && vars.CF_PAGES_PROJECT != ''
    runs-on: ubuntu-26.04
    needs: update-documentation
    environment:
      name: cf-pages-deploy
      deployment: false
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ needs.update-documentation.outputs.artifact-name }}
          path: docs

      - name: Set Up Redirects
        env:
          CF_PAGES_PROJECT: ${{ vars.CF_PAGES_PROJECT }}
        run: |
          : Set Up Redirects
          if [[ -n "${RUNNER_DEBUG:-}" ]]; then set -x; fi
          {
            echo "/previous/27.2 https://obsproject.com/docs/27.2 302"
            echo "/previous/:major.:minor https://:major-:minor.${CF_PAGES_PROJECT}.pages.dev 302"
          } >> "${GITHUB_WORKSPACE}/docs/_redirects"

      - name: Publish To Live Page
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          workingDirectory: ${{ github.workspace }}/docs
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: |-
            pages publish ${{ github.workspace }}/docs
            --project-name=${{ vars.CF_PAGES_PROJECT }}
            --commit-hash=${{ github.sha }}

  sign-windows-build:
    runs-on: ubuntu-26.04
    name: Windows Signing
    steps:
      - run: echo "Hello"

  # sign-windows-build:
  #   name: Windows Signing
  #   uses: obsproject/obs-studio/.github/workflows/sign-windows.yaml@a4a11c3dcdd7f479c8c4d1eb6ed8991fbc54dc6d
  #   if: |-
  #     github.repository_owner == 'obsproject' &&
  #     fromJSON(vars.ENABLE_WINDOWS_CODE_SIGNING || 'false')
  #   needs: build-project
  #   permissions:
  #     contents: read        # Necessary to keep workflow base permissions.
  #     attestations: write   # Necessary to generate an attestation for the code signed build.
  #   secrets:
  #     gcp-identity-pool: ${{ secrets.GCP_IDENTITY_POOL }}
  #     gcp-service-account-name: ${{ secrets.GCP_SERVICE_ACCOUNT_NAME }}

  create-release:
    name: Create Release
    runs-on: ubuntu-26.04
    needs: [build-project, sign-windows-build]
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Generate Semver From Tag
        id: semver
        uses: ./.github/actions/check-version-tag
        with:
          ref: ${{ github.ref_name }}

      - name: Generate Short GitHub SHA
        id: short-sha
        uses: ./.github/actions/generate-short-sha

      - name: Set Up Environment
        id: setup
        env:
          HAS_SEMVER: ${{ fromJSON(steps.semver.outputs.is-valid-semver) }}
        run: |
          if [[ -n "${RUNNER_DEBUG:-}" ]]; then set -x; fi
          if [[ "${HAS_SEMVER:-false}" != 'true' ]]; then
            echo '::error::Current git ref name is not a valid semantic version.'
            return 1
          fi

      - name: Prepare Release Assets
        id: prepare
        uses: ./.github/actions/publish-obs/prepare-release-assets
        with:
          artifact-name: ${{ format('obs-studio-*-{0}', steps.short-sha.outputs.sha) }}
          version: ${{ steps.semver.outputs.version }}
          download-artifacts: true

      - name: Create Release
        uses: ./.github/publish-obs/create-github-release
        with:
          draft: true
          is-prerelease: ${{ steps.semver.outputs.pre-release != null }}
          tag: ${{ steps.semver.outputs.version }}
          name: ${{ format('OBS Studio {0}', steps.semver.outputs.version) }}
          release-note-file: ${{ steps.prepare.outputs.checksum-file }}
          files: ${{ steps.prepare.outputs.release-files }}
