name: Schedule
run-name: Scheduled Repository Actions
on:
  workflow_dispatch:
  schedule:
    - cron: 17 0 * * *
permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash --noprofile --norc -eo errexit -eo pipefail -eo nounset {0}
jobs:
  cache-cleanup:
    name: Cache Cleanup
    runs-on: ubuntu-26.04
    permissions:
      contents: read    # Necessary for repository checkouts.
      actions: write    # Necessary to update and delete stale actions caches
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          submodules: recursive
          fetch-depth: 1

      - name: Remove Compilation Caches
        uses: ./.github/actions/clean-cache
        with:
          name: '(macos|ubuntu-.*)-compilation-(x86_64|arm64)-.*'
          ref: refs/heads/master

  build-project:
    name: Build
    uses: ./.github/workflows/build-project.yaml
    needs: cache-cleanup
    permissions:
      contents: read          # Necessary for repository checkouts.
    with:
      environment: build
    secrets: inherit          # zizmor: ignore[secrets-inherit]

  analyze-project:
    name: Code Analysis
    uses: ./.github/workflows/analyze-project.yaml
    needs: cache-cleanup
    permissions:
      contents: read          # Necessary for repository checkouts.
      security-events: write  # Necessary to post CodeQL security scanning reports
    with:
      environment: nightly
    secrets: inherit          # zizmor: ignore[secrets-inherit]

  services-availability:
    name: Check Service Availability
    if: vars.ENABLE_SERVICE_CHECKS
    runs-on: macos-26
    environment: nightly
    permissions:
      contents: write         # Necessary to push commits to repository
      checks: write           # Necessary to create error annotations
      pull-requests: write    # Necessary to create pull requests
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Check Services
        uses: ./.github/actions/lint-obs/validate-services-data
        with:
          api-token: ${{ secrets.SERVICE_CHECK_API_KEY }}
          api-servers: ${{ secrets.SERVICE_CHECK_SERVERS }}
          run-schema-checks: false
          run-service-checks: true
          create-pull-request: true
          purge-age: ${{ vars.SERVICE_CHECK_PURGE_AGE }}

  upload-language-files:
    name: Upload Language Files
    if: vars.ENABLE_L10N_UPDATE
    runs-on: ubuntu-26.04
    environment: nightly
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          submodules: recursive
          fetch-depth: 0

      - name: Check Nightly Ref
        id: ref-check
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          : Check Nightly Ref
          if [[ "${RUNNER_DEBUG:-}" ]]; then set -x; fi

          declare gh_output
          gh_output="$(gh run list --workflow schedule.yaml --limit 2 --json headSha --jq '.[1].headSha')"

          {
            if [[ "${GITHUB_SHA}" == "${gh_output}" ]]; then
              echo "pass=false"
            else
              echo "pass=true"
              echo "previous-sha=${gh_output}"
            fi
          } >> "${GITHUB_OUTPUT}"

      - name: Check for Changed Files
        if: fromJSON(steps.ref-check.outputs.pass)
        uses: ./.github/actions/check-changes
        id: checks
        with:
          base: ${{ steps.ref-check.outputs.previous-sha }}
          pathspec: '**/en-US.ini'

      - name: Upload US English Language Files
        if: >-
          fromJSON(steps.checks.outputs.has-changed-files)
          && fromJSON(steps.ref-check.outputs.pass)
        uses: obsproject/obs-crowdin-sync/upload@4b488c7ced03aa109d9f12529bd91c26c54b3e89
        env:
          CROWDIN_PAT: ${{ secrets.CROWDIN_SYNC_CROWDIN_PAT || '' }}
          GITHUB_EVENT_BEFORE: ${{ steps.ref-check.outputs.previous-sha }}
